jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_ACCOUNT', 'dummy') }}"
      user: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_USER', 'dummy') }}"
      private_key: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_PRIVATE_KEY', 'dummy') }}"
      private_key_passphrase: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', 'dummy') }}"
      role: SYSADMIN
      database: KITAGAWA_TEST_DB
      warehouse: X_SMALL_WH
      schema: DAGSTER_DBT_SAMPLE
      threads: 1
      client_session_keep_alive: False
      query_tag: cm_kitagawa_dagster